### PR TITLE
Custom nikgapps config file

### PR DESCRIPTION
**Pull request by Nakamerica**
customised nikgapps.config file for custom nikgapps package.

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 13/anmol_nikgapps.config is on version 22 which is not the latest version of NikGapps Config, please update the config file to version 23

Kindly make the changes and send the pull request again!

**Comment by Nakamerica** [comment]
hey, the latest version on sourceforge is v22: 

image

**Comment by nikhilmenghani** [comment]
https://sourceforge.net/projects/nikgapps/files/Releases/Config/NikGapps-T/

you can get the latest version from here

**Comment by Nakamerica** [comment]
thank you.

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 13/anmol_nikgapps.config is on version 22 which is not the latest version of NikGapps Config, please update the config file to version 23

Kindly make the changes and send the pull request again!

**Comment by nikhilmenghani** [comment]
@Nakamerica I suggest you create a new PR with v23 and close this one.

**Pull request closed without merging**
