### PR TITLE
android12.1-debloat

### PR DESCRIPTION
**Pull request by rosemaryuser**
thanks for creating this.

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 12.1/edited.config, You cannot enable both Core and Core Go, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by rosemaryuser** [comment]
oh sorry i updated it

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 12.1/edited.config, All the packages under Google Chrome needs to be enabled, you cannot disable any of the packages under Google Chrome.
Either enable all or disable all.

Kindly make the changes and send the pull request again!

**Comment by rosemaryuser** [comment]
how bout now? sorry for the inconvenience

**Pull request merged**
