### PR TITLE
canasdev-gapps

### PR DESCRIPTION
**Pull request by davidcanas**
<3 Thx Nik

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 14/canasdev.config: You cannot enable both PixelSetupWizard and SetupWizard 'AppSets' simultaneously; only one can be enabled. If you're opting for PixelSetupWizard, ensure that all packages under SetupWizard are also enabled, since PixelSetupWizard and SetupWizard share the same packages.

Kindly make the changes and send the pull request again!

**Comment by davidcanas** [comment]
@nikgapps , Done :D

**Comment by davidcanas** [comment]
Idk if I changed it right haha

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 14/canasdev.config, All the packages under Google Chrome needs to be enabled, you cannot disable any of the packages under Google Chrome.
Either enable all or disable all.
- Update 14/canasdev.config: You cannot enable both PixelSetupWizard and SetupWizard 'AppSets' simultaneously; only one can be enabled. If you're opting for PixelSetupWizard, ensure that all packages under SetupWizard are also enabled, since PixelSetupWizard and SetupWizard share the same packages.

Kindly make the changes and send the pull request again!

**Comment by davidcanas** [comment]
Done again

**Pull request merged**
