### PR TITLE
Ghostnikgapps

### PR DESCRIPTION
**Pull request by Saviourghost**
Thanks nik

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 13/Ghostnikgapps.config, You cannot enable both Pixel Setup Wizard and Setup Wizard, you can only enable one of them
- nikgapps.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by Saviourghost** [comment]
Thank you  very much nik

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 13/Ghostnikgapps.config, You cannot enable both Pixel Setup Wizard and Setup Wizard, you can only enable one of them
- nikgapps.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
Closing as no action was performed in last 24 hours

**Pull request closed without merging**
