### PR TITLE
update basic-shusky and full-shusky

### PR DESCRIPTION
**Pull request by ionutgherman**

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update elite/14/ionut/basic-shusky.config: You cannot enable both PixelSetupWizard and SetupWizard 'AppSets' simultaneously; only one can be enabled. If you're opting for PixelSetupWizard, ensure that all packages under SetupWizard are also enabled, since PixelSetupWizard and SetupWizard share the same packages.
- Update elite/14/ionut/full-shusky.config: You cannot enable both PixelSetupWizard and SetupWizard 'AppSets' simultaneously; only one can be enabled. If you're opting for PixelSetupWizard, ensure that all packages under SetupWizard are also enabled, since PixelSetupWizard and SetupWizard share the same packages.

Kindly make the changes and send the pull request again!

**Comment by ionutgherman** [comment]
Updated again

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update elite/14/ionut/basic-shusky.config: You cannot enable both PixelSetupWizard and SetupWizard 'AppSets' simultaneously; only one can be enabled. If you're opting for PixelSetupWizard, ensure that all packages under SetupWizard are also enabled, since PixelSetupWizard and SetupWizard share the same packages.
- Update elite/14/ionut/full-shusky.config: You cannot enable both PixelSetupWizard and SetupWizard 'AppSets' simultaneously; only one can be enabled. If you're opting for PixelSetupWizard, ensure that all packages under SetupWizard are also enabled, since PixelSetupWizard and SetupWizard share the same packages.

Kindly make the changes and send the pull request again!

**Comment by ionutgherman** [comment]
2nd update should take it

**Pull request merged**
