### PR TITLE
Updated Config (for LineageOS 20)

### PR DESCRIPTION
**Pull request by user090**
This is specially created for LineageOS 20. But can be usable on any de-Googled Android 13 custom ROM :).

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 13/user090(LineageOS20).config is not an aphanumeric name, make sure the name of config file is between A-Z and 0-9 additionally, accepted symbols are - (dash) or _ (underscore) any symbols including but not limited to (, ' . # ! *) or space are not accepted in the name try renaming the file to a name that doesn't contain any spaces or special characters
- Update 13/user090(LineageOS20).config, You cannot enable both Pixel Setup Wizard and Setup Wizard, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by user090** [comment]
Changing the name by removing () and replacing them with underscore.
This is specially created for LineageOS 20 ROM and for that, some apps are got deleted. But it can be usable for any other Android 13-based de-Googled custom ROM.

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 13/user090_LineageOS20.config, You cannot enable both Pixel Setup Wizard and Setup Wizard, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by user090** [comment]
Changed the parameter of PixelSetupWizard from 1 to 0.

**Pull request merged**
