### PR TITLE
Devils gapps

### PR DESCRIPTION
**Pull request by ToxicPBX1**
Thx nik

### CODE REVIEW

**Comment by nikhilmenghani** [comment]
@ToxicPBX1 we can't accept the pull request as long as you have file outside of 10 or 11 folder. Please create a fresh pull request, add your files by doing exactly as shown in the video.

**Comment by ToxicPBX1** [comment]
But i added confis in a10 folder

**Comment by ToxicPBX1** [comment]
> @ToxicPBX1 we can't accept the pull request as long as you have file outside of 10 or 11 folder. But i added confis in a10 folder create a fresh pull request, add your files by doing exactly as shown in the video

> @ToxicPBX1 we can't accept the pull request as long as you have file outside of 10 or 11 folder. Please create a fresh pull request, add your files by doing exactly as shown in the video.

But i added confis in a10 folder

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- You cannot modify archived file archive/10/toxic PBX1.config
- toxic PBX1.config must be part of Android Version folder, not outside of it!
- toxic.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Pull request closed without merging**
