### PR TITLE
kammkarp1-gapps

### PR DESCRIPTION
**Pull request by kammkarp1**
Thx Nik for your amazing work

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 13/kammkarp1.config, You cannot enable both Pixel Setup Wizard and Setup Wizard, you can only enable one of them
- Update 13/kammkarp1.config, You cannot enable both Core and Core Go, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by kammkarp1** [comment]
• Update 13/kammkarp1.config Bugs fixed.
• Update 13/kammkarpdev Updated to v30.

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 13/kammkarp1.config is on version 30 which is not the latest version of NikGapps Config, please download the [latest version](https://sourceforge.net/projects/nikgapps/files/Releases/Config/NikGapps-T/v29/) and update the config file to version 29. Sucks, I know! but you can become [NikGapps Elite](https://nikgapps.com/misc/2023/06/08/NikGapps-Elites.html) and get rid of this hassle. The config will be auto upgraded to latest version.

Kindly make the changes and send the pull request again!

**Comment by kammkarp1** [comment]
13/kammkarp1 Fixed.

**Pull request merged**
