### PR TITLE
Toxic gapps

### PR DESCRIPTION
**Pull request by ToxicPBX1**
Nik thx for ur hardwork

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- toxic PBX1.config must be part of Android Version folder, not outside of it!
- toxic.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by ToxicPBX1** [comment]
How to make it a part

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- toxic PBX1.config must be part of Android Version folder, not outside of it!
- toxic.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by nikhilmenghani** [comment]
@ToxicPBX1 go inside 11 or 10 folder before uploading your config file. Watch following video for detailed steps. 

https://youtu.be/jZWR9Wz7hMk

**Pull request closed without merging**
