### PR TITLE
Orel6505-NikGapps

### PR DESCRIPTION
**Pull request by Orel6505**

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 10/placeholder doesn't have .config extension, we only accept config files!
- Cannot merge the changes automatically since 10/placeholder is either modified or removed, Wait for someone to manually review!
- 11/placeholder doesn't have .config extension, we only accept config files!
- Cannot merge the changes automatically since 11/placeholder is either modified or removed, Wait for someone to manually review!

Kindly make the changes and send the pull request again!

**Comment by Orel6505** [comment]
you can try again please?

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 10/placeholder doesn't have .config extension, we only accept config files!
- Cannot merge the changes automatically since 10/placeholder is either modified or removed, Wait for someone to manually review!
- 11/placeholder doesn't have .config extension, we only accept config files!
- Cannot merge the changes automatically since 11/placeholder is either modified or removed, Wait for someone to manually review!

Kindly make the changes and send the pull request again!

**Comment by nikhilmenghani** [comment]
@Orel6505 create a fresh new pull request with only your changes.

**Pull request closed without merging**
