### PR TITLE
Create nikgapps88.config

### PR DESCRIPTION
**Pull request by asabouriyan**
hi . its me again . thanks
is this ok now ?

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- nikgapps88.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by asabouriyan** [comment]
how i should do that ?

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- nikgapps88.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
Closing as no action was performed in last 24 hours

**Pull request closed without merging**
