### PR TITLE
gapps1

### PR DESCRIPTION
**Pull request by Homer91**
Hey Nik, thk for all the hardwork.

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 13/ gapps1.config is not an aphanumeric name, make sure the name of config file is between A-Z and 0-9 additionally, accepted symbols are - (dash) or _ (underscore) any symbols including but not limited to (, ' . # ! *) or space are not accepted in the name try renaming the file to a name that doesn't contain any spaces or special characters
- Update 13/ gapps1.config, You cannot enable both Pixel Setup Wizard and Setup Wizard, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by Homer91** [comment]
Hi Nik, I've made the edits, hope all goes well, thanks for your patience.

**Comment by Homer91** [comment]
Hi Nik, I've made the edits, hope all goes well, thanks for your patience

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 13/ gapps1.config is not an aphanumeric name, make sure the name of config file is between A-Z and 0-9 additionally, accepted symbols are - (dash) or _ (underscore) any symbols including but not limited to (, ' . # ! *) or space are not accepted in the name try renaming the file to a name that doesn't contain any spaces or special characters
- Update 13/ gapps1.config, You cannot enable both Pixel Setup Wizard and Setup Wizard, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
Closing as no action was performed in last 24 hours

**Pull request closed without merging**
