### PR TITLE
SA_chin's lite

### PR DESCRIPTION
**Pull request by SA-chin-2003**
Actually you are working pretty well. You made this custom package making so easy. Thanks

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- SA_chin's lite.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by nikhilmenghani** [comment]
@SA-chin-2003 thanks! Can you also ensure you don't use symbols on your config name? To avoid potential errors with your build?

**Comment by SA-chin-2003** [comment]
> @SA-chin-2003 thanks! Can you also ensure you don't use symbols on your config name? To avoid potential errors with your build?

Ok sir,will look upon it

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- SA_chin's lite.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by nikhilmenghani** [comment]
@SA-chin-2003 the file changes tab in this pull request has 2 files changed. The pull request will not be merged until the file which is outside of 11 folder is deleted.

**Comment by nikhilmenghani** [comment]
Closing since no action on PR

**Pull request closed without merging**
