### PR TITLE
OnlyPixelLauncher

### PR DESCRIPTION
**Pull request by LearningXpress**

### CODE REVIEW

**Comment by nikhilmenghani** [comment]
@LearningXpress your package will be created but why not just download pixel launcher addon?

**Comment by LearningXpress** [comment]
I Didn't See any Addon For only Pixel Launcher.If that Possible Can Give The Link.

**Comment by LearningXpress** [comment]
> @LearningXpress your package will be created but why not just download pixel launcher addon?

I Didn't See any Addon For only Pixel Launcher.If that Possible Can Give The Link.

**Comment by nikhilmenghani** [comment]
@LearningXpress https://sourceforge.net/projects/nikgapps/files/Releases/Addons-R/11-Jul-2021/

Look for a file with pixel launcher in its name.

**Comment by LearningXpress** [comment]
> @LearningXpress https://sourceforge.net/projects/nikgapps/files/Releases/Addons-R/11-Jul-2021/
> 
> Look for a file with pixel launcher in its name.

Can I Flashit Directly Without any Other Packages In AOSP Roms?

**Pull request merged**
