### PR TITLE
Fullv2-A14-L21-MrHLeo92

### PR DESCRIPTION
**Pull request by MrHLeo**
umm thx bro

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 14/FULL-MrHLeo92.config: PixelSetupWizard and SetupWizard 'AppSets' cannot be enabled at the same time; only one can be active. If you choose PixelSetupWizard, make sure to enable all packages under SetupWizard as well, since PixelSetupWizard and SetupWizard use the same packages.
- Update 14/FULL-MrHLeo92.config, You cannot enable both Core and Core Go, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by MrHLeo** [comment]
I understand. Unfortunately, I still need to improve my English. I’m also learning how to do this on my old phone. I want to install LineageOS 21 with Android 14 and Full Gapps on a Samsung Galaxy Note10+, but I'm not sure what settings I should enable. I will do some more research now.

**Comment by MrHLeo** [comment]
oh and i used Microsoft Launcher

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 14/FULL-MrHLeo92.config: PixelSetupWizard and SetupWizard 'AppSets' cannot be enabled at the same time; only one can be active. If you choose PixelSetupWizard, make sure to enable all packages under SetupWizard as well, since PixelSetupWizard and SetupWizard use the same packages.

Kindly make the changes and send the pull request again!

**Comment by MrHLeo** [comment]
@MrHLeo
[FULLv2-MrHLeo92.config](https://github.com/nikgapps/config/pull/11858/commits/f94408983f8b2a92f7e2b6ca71fc1a9ece8f8a3c)

**Comment by MrHLeo** [comment]
Could you make one that can replace LineageOS apps for example * Microsoft Launcher and office: word, power point, excel * Google Calculator * File Manager replaced by Google Files Could you help me learn this?

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 14/FULL-MrHLeo92.config: PixelSetupWizard and SetupWizard 'AppSets' cannot be enabled at the same time; only one can be active. If you choose PixelSetupWizard, make sure to enable all packages under SetupWizard as well, since PixelSetupWizard and SetupWizard use the same packages.

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
Closing as no action was performed in last 24 hours
Kindly make the changes and send the pull request again!

**Pull request closed without merging**
