### PR TITLE
Update EliteBuilds.yml

### PR DESCRIPTION
**Pull request by CanerKaraca23**

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- .github/workflows/EliteBuilds.yml must be part of Android Version folder, not outside of it!
- Cannot merge the changes automatically since status of .github/workflows/EliteBuilds.yml is modified, kindly start fresh with forking the repository again!

Kindly make the changes and send the pull request again!

**Comment by CanerKaraca23** [comment]
You can manually update it, as PR cannot be merged.

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- .github/workflows/EliteBuilds.yml must be part of Android Version folder, not outside of it!
- Cannot merge the changes automatically since status of .github/workflows/EliteBuilds.yml is modified, kindly start fresh with forking the repository again!

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
@CanerKaraca23 my bad, I should have excluded this yml file from config validation. I will merge the changes manually.

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 my bad, I should have excluded this yml file from config validation. I will merge the changes manually.

No problem, thanks. I just want to help you to keep all things up-to-date.

**Comment by nikhilmenghani** [comment]
> > @CanerKaraca23 my bad, I should have excluded this yml file from config validation. I will merge the changes manually.
> 
> No problem, thanks. I just want to help you to keep all things up-to-date.

Thanks it helps! (y)

**Pull request merged**
