### PR TITLE
Custom (almost full set) of nikgapps repository

### PR DESCRIPTION
**Pull request by mcurly**
Hello, 
Thank you to everyone who contributed.
Hope this request pulls through and wish  you all the best!

Cheers!

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 12.1/mccurly-full-custom-gapps-12_1.config is on version 22 which is not the latest version of NikGapps Config, please update the config file to version 26

Kindly make the changes and send the pull request again!

**Comment by mcurly** [comment]
Hello, sorry, my bad, I thought (wrongly, I know already), by trying to pull the newest version of Android 13, that (automatically) the version  for 12.1, that I had previously, would be (automatically, again), archived...

Sorry then. I will fix immediately.

Thank you!

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- You cannot modify archived file archive/mccurly-full-custom-gapps-12_1.config
- archive/mccurly-full-custom-gapps-12_1.config is on version 22 which is not the latest version of NikGapps Config, please update the config file to version 26

Kindly make the changes and send the pull request again!

**Comment by mcurly** [comment]
Immediately... took a while. Apologies. Since I am a noob, I had to look for a way to move the conflicting 12.1 config file to archive. (I assume I am doing it right).
Thank you again.

Cheers!

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- You cannot modify archived file archive/mccurly-full-custom-gapps-12_1.config
- archive/mccurly-full-custom-gapps-12_1.config is on version 22 which is not the latest version of NikGapps Config, please update the config file to version 26

Kindly make the changes and send the pull request again!

**Pull request closed without merging**
