### PR TITLE
Devils 👿

### PR DESCRIPTION
**Pull request by ToxicPBX1**
Thx devil sorry 😐 nik...

### CODE REVIEW

**Comment by ToxicPBX1** [comment]
I want to upload file in ur a10 folder?

**Comment by ToxicPBX1** [comment]
Want to add in ur branch

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- You cannot modify archived file archive/10/toxic PBX1.config
- toxic PBX1.config must be part of Android Version folder, not outside of it!
- toxic.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by nikhilmenghani** [comment]
@ToxicPBX1 Please delete your config repository and start fresh, you are still adding the config files in root folder. The "Files Changed" tab must only have the files which you want to build your custom build out of. 

Kindly delete the repository, follow the steps from munchy's video and try again

**Pull request closed without merging**
