### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ravan6**

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 13/thunderr.config, You cannot enable both Core and Core Go, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by ravan6** [comment]
Thnx

**Comment by ravan6** [comment]
Thnx

**Comment by ravan6** [comment]
Thn

**Comment by ravan6** [comment]
Thanks

**Pull request merged**
