### PR TITLE
Chrome Package without Chrome browser ; CrDroid10-A14-F2Pro-K30Pro-lmi_jason-eu.config

### PR DESCRIPTION
**Pull request by jason-eu**
@nikgapps @nikhilmenghani 

I finally settled on the config I wanted to make 😃

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 14/CrDroid10-A14-F2Pro-K30Pro-lmi_jason-eu.config, All the packages under Google Chrome needs to be enabled, you cannot disable any of the packages under Google Chrome.
Either enable all or disable all.

Kindly make the changes and send the pull request again!

**Comment by nikhilmenghani** [comment]
@jason-eu merging the changes but I encourage you to use smaller config name. Few of the details will already be there in the output name. Such as android version.

**Comment by jason-eu** [comment]
Thank you. Ok, maybe I'll reduce it to ;
CrDroid10-A14_lmi_jason-eu.config

Woul that be ok?

**Comment by jason-eu** [comment]
I understand, even more so now seeing how comical the file name length looks with the full name.

I will settle on ;
CrDroid10_jason-eu_lmi.config

To get ;
NikGapps-CrDroid10_jason-eu_lmi-arm64-14-20231205.zip

Well next time that is, I need to figure out how to rename an already uploaded file.
Or maybe I'll wait until I have changes and upload a new one, with a request to delete the latter.

Will try renaming first, seems like less steps to go through.

Thank you !

**Pull request merged**
