### PR TITLE
DhoniJNU.gapps

### PR DESCRIPTION
**Pull request by DhoniJNU**
thanxx buddy .. nik

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 10/DhoniJNU.config, You cannot enable both Core and Core Go, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by DhoniJNU** [comment]
i have uploaded.

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 10/DhoniJNU.config, You cannot enable both Core and Core Go, you can only enable one of them
- DhoniJNU-gapps- without- google diler.config must be part of Android Version folder, not outside of it!
- DhoniJNU-gapps- without- google diler.config is not an aphanumeric name, make sure the name of config file is between A-Z and 0-9 additionally, accepted symbols are - (dash) or _ (underscore) any symbols including but not limited to (, ' . # ! *) or space are not accepted in the name try renaming the file to a name that doesn't contain any spaces or special characters
- Update DhoniJNU-gapps- without- google diler.config, You cannot enable both Core and Core Go, you can only enable one of them
- DhoniJNU.config must be part of Android Version folder, not outside of it!
- Update DhoniJNU.config, You cannot enable both Core and Core Go, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
Closing as no action was performed in last 24 hours

**Pull request closed without merging**
