### PR TITLE
Delete crDroidGapps.config

### PR DESCRIPTION
**Pull request by vivekvijayan20**

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Cannot merge the changes automatically since status of elite/13/Sinister/crDroidGapps.config is removed, kindly start fresh with forking the repository again!

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
@vivekvijayan20 would you like me to delete the file? may I know why you are deleting it?

**Comment by nikgapps** [comment]
Your file is deleted

**Comment by vivekvijayan20** [comment]
I already gave a config file inside my folder. As my builds aren't uploaded on sourceforge, I thought it was a problem in config file.

**Pull request merged**
