### PR TITLE
sigapps-mod-a13-20241004

### PR DESCRIPTION
**Pull request by sijp26**
thanks dev

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 13/nikgapps-mod-a13-20241004.config, You cannot enable both Core and Core Go, you can only enable one of them

Kindly make the changes and send the pull request again!

**Comment by sijp26** [comment]
Sorry for this kind of mistake sir. I will correct this.

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 13/nikgapps-a13-20241004 doesn't have .config extension, we only accept config files!

Kindly make the changes and send the pull request again!

**Comment by sijp26** [comment]
I am sorry. I am actually new to git. I am going to change it sir.

**Pull request merged**
