### PR TITLE
Saviour.config

### PR DESCRIPTION
**Pull request by Saviour5**
Thank you nik

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- nikgapps.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by Saviour5** [comment]
Cool

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- nikgapps.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by Saviour5** [comment]
Is this fine know don't know what's wrong

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- nikgapps.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Pull request closed without merging**
