### PR TITLE
DarkGapps

### PR DESCRIPTION
**Pull request by DaoOfDarkness**

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 10/placeholder doesn't have .config extension, we only accept config files!
- Cannot merge the changes automatically since 10/placeholder is either modified or removed, Wait for someone to manually review!
- 11/placeholder doesn't have .config extension, we only accept config files!
- Cannot merge the changes automatically since 11/placeholder is either modified or removed, Wait for someone to manually review!
- README.md doesn't have .config extension, we only accept config files!
- README.md must be part of Android Version folder, not outside of it!
- Cannot merge the changes automatically since README.md is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/210717SM-T510_20210717.config
- Cannot merge the changes automatically since archive/10/210717SM-T510_20210717.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/210717SM-T510_20210807.config
- Cannot merge the changes automatically since archive/10/210717SM-T510_20210807.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/210717bSM-T510_20210717.config
- Cannot merge the changes automatically since archive/10/210717bSM-T510_20210717.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/210717bSM-T510_20210807.config
- Cannot merge the changes automatically since archive/10/210717bSM-T510_20210807.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/210807ASUS_20210807.config
- Cannot merge the changes automatically since archive/10/210807ASUS_20210807.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/ABC-NikGapps-10_20210902.config
- Cannot merge the changes automatically since archive/10/ABC-NikGapps-10_20210902.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/AayanCustom_20210720.config
- Cannot merge the changes automatically since archive/10/AayanCustom_20210720.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alcospy_20210828.config
- Cannot merge the changes automatically since archive/10/Alcospy_20210828.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alok-sep18ultra_20210918.config
- Cannot merge the changes automatically since archive/10/Alok-sep18ultra_20210918.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alok_RR_20210801.config
- Cannot merge the changes automatically since archive/10/Alok_RR_20210801.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alok_RR_20210808.config
- Cannot merge the changes automatically since archive/10/Alok_RR_20210808.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alok_Rr_20210817.config
- Cannot merge the changes automatically since archive/10/Alok_Rr_20210817.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alok_sep11_20210911.config
- Cannot merge the changes automatically since archive/10/Alok_sep11_20210911.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun-RRosA10-Ginkgo_20210721.config
- Cannot merge the changes automatically since archive/10/Alokpupun-RRosA10-Ginkgo_20210721.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun-RrOs-A10-ginkgo_20210724.config
- Cannot merge the changes automatically since archive/10/Alokpupun-RrOs-A10-ginkgo_20210724.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun_20210715.config
- Cannot merge the changes automatically since archive/10/Alokpupun_20210715.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun_20210717.config
- Cannot merge the changes automatically since archive/10/Alokpupun_20210717.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun_20210718.config
- Cannot merge the changes automatically since archive/10/Alokpupun_20210718.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun_A10_20210729.config
- Cannot merge the changes automatically since archive/10/Alokpupun_A10_20210729.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/AramunA10_20210925.config
- Cannot merge the changes automatically since archive/10/AramunA10_20210925.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Aramun_20210808.config
- Cannot merge the changes automatically since archive/10/Aramun_20210808.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/AshbornFrosty_20210719.config
- Cannot merge the changes automatically since archive/10/AshbornFrosty_20210719.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Bloodshot_20210713.config
- Cannot merge the changes automatically since archive/10/Bloodshot_20210713.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/C1RMX1811_20210427.config
- Cannot merge the changes automatically since archive/10/C1RMX1811_20210427.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/C1RMX1811_20210428.config
- Cannot merge the changes automatically since archive/10/C1RMX1811_20210428.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/CPGapps_20210711.config
- Cannot merge the changes automatically since archive/10/CPGapps_20210711.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Chandler_10_20210828.config
- Cannot merge the changes automatically since archive/10/Chandler_10_20210828.config is either modified or removed, Wait for someone to manually review!

Kindly make the changes and send the pull request again!

**Comment by DaoOfDarkness** [comment]
Sorry, I messed up the instructions

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 10/placeholder doesn't have .config extension, we only accept config files!
- Cannot merge the changes automatically since 10/placeholder is either modified or removed, Wait for someone to manually review!
- 11/placeholder doesn't have .config extension, we only accept config files!
- Cannot merge the changes automatically since 11/placeholder is either modified or removed, Wait for someone to manually review!
- README.md doesn't have .config extension, we only accept config files!
- README.md must be part of Android Version folder, not outside of it!
- Cannot merge the changes automatically since README.md is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/210717SM-T510_20210717.config
- Cannot merge the changes automatically since archive/10/210717SM-T510_20210717.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/210717SM-T510_20210807.config
- Cannot merge the changes automatically since archive/10/210717SM-T510_20210807.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/210717bSM-T510_20210717.config
- Cannot merge the changes automatically since archive/10/210717bSM-T510_20210717.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/210717bSM-T510_20210807.config
- Cannot merge the changes automatically since archive/10/210717bSM-T510_20210807.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/210807ASUS_20210807.config
- Cannot merge the changes automatically since archive/10/210807ASUS_20210807.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/ABC-NikGapps-10_20210902.config
- Cannot merge the changes automatically since archive/10/ABC-NikGapps-10_20210902.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/AayanCustom_20210720.config
- Cannot merge the changes automatically since archive/10/AayanCustom_20210720.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alcospy_20210828.config
- Cannot merge the changes automatically since archive/10/Alcospy_20210828.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alok-sep18ultra_20210918.config
- Cannot merge the changes automatically since archive/10/Alok-sep18ultra_20210918.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alok_RR_20210801.config
- Cannot merge the changes automatically since archive/10/Alok_RR_20210801.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alok_RR_20210808.config
- Cannot merge the changes automatically since archive/10/Alok_RR_20210808.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alok_Rr_20210817.config
- Cannot merge the changes automatically since archive/10/Alok_Rr_20210817.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alok_sep11_20210911.config
- Cannot merge the changes automatically since archive/10/Alok_sep11_20210911.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun-RRosA10-Ginkgo_20210721.config
- Cannot merge the changes automatically since archive/10/Alokpupun-RRosA10-Ginkgo_20210721.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun-RrOs-A10-ginkgo_20210724.config
- Cannot merge the changes automatically since archive/10/Alokpupun-RrOs-A10-ginkgo_20210724.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun_20210715.config
- Cannot merge the changes automatically since archive/10/Alokpupun_20210715.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun_20210717.config
- Cannot merge the changes automatically since archive/10/Alokpupun_20210717.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun_20210718.config
- Cannot merge the changes automatically since archive/10/Alokpupun_20210718.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Alokpupun_A10_20210729.config
- Cannot merge the changes automatically since archive/10/Alokpupun_A10_20210729.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/AramunA10_20210925.config
- Cannot merge the changes automatically since archive/10/AramunA10_20210925.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Aramun_20210808.config
- Cannot merge the changes automatically since archive/10/Aramun_20210808.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/AshbornFrosty_20210719.config
- Cannot merge the changes automatically since archive/10/AshbornFrosty_20210719.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Bloodshot_20210713.config
- Cannot merge the changes automatically since archive/10/Bloodshot_20210713.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/C1RMX1811_20210427.config
- Cannot merge the changes automatically since archive/10/C1RMX1811_20210427.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/C1RMX1811_20210428.config
- Cannot merge the changes automatically since archive/10/C1RMX1811_20210428.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/CPGapps_20210711.config
- Cannot merge the changes automatically since archive/10/CPGapps_20210711.config is either modified or removed, Wait for someone to manually review!
- You cannot modify archived file archive/10/Chandler_10_20210828.config
- Cannot merge the changes automatically since archive/10/Chandler_10_20210828.config is either modified or removed, Wait for someone to manually review!

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
Closing as no action was performed in last 24 hours

**Pull request closed without merging**
