### PR TITLE
sameer-gapps

### PR DESCRIPTION
**Pull request by sam582**

### CODE REVIEW

**Comment by sam582** [comment]
SameerGapps

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- SameerGapps.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by sam582** [comment]
Sameer-Gapps-2.0

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- SameerGapps.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Pull request closed without merging**
