### PR TITLE
gojo-san.config

### PR DESCRIPTION
**Pull request by Slimreapee24**
Hey nik, thanks for all the hard work

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- gojo-san.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by Slimreapee24** [comment]
I already changed please see it thanks

**Comment by Slimreapee24** [comment]
Hi, i already made the changes thanks

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- A13 must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Pull request closed without merging**
