### PR TITLE
lineageosa12L

### PR DESCRIPTION
**Pull request by ishu179**
:) :) :) :)

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 12.1/lineage19.1a12.1.config is not an aphanumeric name, make sure the name of config file is between A-Z and 0-9 additionally, accepted symbols are - (dash) or _ (underscore) any symbols including but not limited to (, ' . # ! *) are not accepted in the name
- 12/ishu-pixelL.config is not on the latest version of NikGapps Config, please update the config file to version 23

Kindly make the changes and send the pull request again!

**Comment by ishu179** [comment]
ishulineageosa12L

**Comment by ishu179** [comment]
mistakes removed :)

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 12/ishu-pixelL.config is not on the latest version of NikGapps Config, please update the config file to version 23

Kindly make the changes and send the pull request again!

**Pull request closed without merging**
