### PR TITLE
hieu-gapps-2023

### PR DESCRIPTION
**Pull request by hieunv271**
Hey nik thank for all hardwork

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 11/hieudeptrai.config is on version 22 which is not the latest version of NikGapps Config, please download the [latest version](https://sourceforge.net/projects/nikgapps/files/Releases/Config/NikGapps-R/v30/) and update the config file to version 30. Sucks, I know! but you can become [NikGapps Elite](https://nikgapps.com/misc/2023/06/08/NikGapps-Elites.html) and get rid of this hassle. The config will be auto upgraded to latest version.
- Cannot merge the changes automatically since status of 12/placeholder is removed, kindly start fresh with forking the repository again!
- 12/placeholder doesn't have .config extension, we only accept config files!

Kindly make the changes and send the pull request again!

**Comment by hieunv271** [comment]
ok, thank you, i'll do it again

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Cannot merge the changes automatically since status of 12/placeholder is removed, kindly start fresh with forking the repository again!
- 12/placeholder doesn't have .config extension, we only accept config files!

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
Closing as no action was performed in last 24 hours

**Pull request closed without merging**
