### PR TITLE
Hi

### PR DESCRIPTION
**Pull request by NgocDuc2010**
Im just build Gapps for my old phones. Please do an Gapps for me. Thanks

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 11/GrandPrime.config, You cannot enable both Core and Core Go, you can only enable one of them
- 14/duc201001lite.config is on version 35 which is not the latest version of NikGapps Config, please download the [latest version](https://sourceforge.net/projects/nikgapps/files/NikGappsConfigs/Android-14/v36/) and update the config file to version 36.
- Update 14/duc201001lite.config, You cannot enable both Core and Core Go, you can only enable one of them
- 14/duck_201001.config is on version 35 which is not the latest version of NikGapps Config, please download the [latest version](https://sourceforge.net/projects/nikgapps/files/NikGappsConfigs/Android-14/v36/) and update the config file to version 36.

Kindly make the changes and send the pull request again!

Mismatched config version Sucks, I know! but you can become [NikGapps Elite](https://nikgapps.com/misc/2023/06/08/NikGapps-Elites.html) and get rid of this hassle. The config will be auto upgraded to latest version.

**Comment by NgocDuc2010** [comment]
Add Android11Go.config

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 11/Android11Go.config: PixelSetupWizard and SetupWizard 'AppSets' cannot be enabled at the same time; only one can be active. If you choose PixelSetupWizard, make sure to enable all packages under SetupWizard as well, since PixelSetupWizard and SetupWizard use the same packages.
- Update 11/GrandPrime.config, You cannot enable both Core and Core Go, you can only enable one of them
- 14/duc201001lite.config is on version 35 which is not the latest version of NikGapps Config, please download the [latest version](https://sourceforge.net/projects/nikgapps/files/NikGappsConfigs/Android-14/v36/) and update the config file to version 36.
- Update 14/duc201001lite.config, You cannot enable both Core and Core Go, you can only enable one of them
- 14/duck_201001.config is on version 35 which is not the latest version of NikGapps Config, please download the [latest version](https://sourceforge.net/projects/nikgapps/files/NikGappsConfigs/Android-14/v36/) and update the config file to version 36.

Kindly make the changes and send the pull request again!

Mismatched config version Sucks, I know! but you can become [NikGapps Elite](https://nikgapps.com/misc/2023/06/08/NikGapps-Elites.html) and get rid of this hassle. The config will be auto upgraded to latest version.

**Comment by NgocDuc2010** [comment]
Android11Go.config has change: PixelSetupWizard set to 0

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- Update 11/GrandPrime.config, You cannot enable both Core and Core Go, you can only enable one of them
- 14/duc201001lite.config is on version 35 which is not the latest version of NikGapps Config, please download the [latest version](https://sourceforge.net/projects/nikgapps/files/NikGappsConfigs/Android-14/v36/) and update the config file to version 36.
- Update 14/duc201001lite.config, You cannot enable both Core and Core Go, you can only enable one of them
- 14/duck_201001.config is on version 35 which is not the latest version of NikGapps Config, please download the [latest version](https://sourceforge.net/projects/nikgapps/files/NikGappsConfigs/Android-14/v36/) and update the config file to version 36.

Kindly make the changes and send the pull request again!

Mismatched config version Sucks, I know! but you can become [NikGapps Elite](https://nikgapps.com/misc/2023/06/08/NikGapps-Elites.html) and get rid of this hassle. The config will be auto upgraded to latest version.

**Comment by NgocDuc2010** [comment]
Delete things

**Pull request merged**
