### PR TITLE
songmiao8888-gapps

### PR DESCRIPTION
**Pull request by songmiao8888**
thank you

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- laodaye212.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by songmiao8888** [comment]
thank you

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- laodaye212.config must be part of Android Version folder, not outside of it!

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
Closing as no action was performed in last 24 hours

**Pull request closed without merging**
