### PR TITLE
update Albgapps

### PR DESCRIPTION
**Pull request by cocka11**

### CODE REVIEW

**Comment by cocka11** [comment]
it's fixed now.

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- 11/AlbGapps.config is on version 22 which is not the latest version of NikGapps Config, please update the config file to version 23
- 12/AlbGapps.config is on version 20 which is not the latest version of NikGapps Config, please update the config file to version 23

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
Closing as no action was performed in last 24 hours

**Comment by cocka11** [comment]
why??

**Pull request closed without merging**
