### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by KesunyianAyam**
update the link to latest gapps config file blog post guide

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- README.md doesn't have .config extension, we only accept config files!
- README.md must be part of Android Version folder, not outside of it!
- Cannot merge the changes automatically since README.md is either modified or removed, Wait for someone to manually review!

Kindly make the changes and send the pull request again!

**Comment by KesunyianAyam** [comment]
@nikhilmenghani proposed change is at the first comment, bot not needed lmao

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- README.md doesn't have .config extension, we only accept config files!
- README.md must be part of Android Version folder, not outside of it!
- Cannot merge the changes automatically since README.md is either modified or removed, Wait for someone to manually review!

Kindly make the changes and send the pull request again!

**Comment by nikhilmenghani** [comment]
@KesunyianAyam lol, yeah, gotta fix this in bot too. Thanks for the pull request, I'll merge it soon.

**Pull request merged**
