### PR TITLE
Create PrivateGappsElitRMX1911.config

### PR DESCRIPTION
**Pull request by Namikazetoto**
make a pull request, please add admin nikgapps 🙏🙏

### CODE REVIEW

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- elite/10/PrivateGappsElitRMX1911.config is not a valid path, make sure your elite config is in elite/<android_version>/<elite_folder_name>

Kindly make the changes and send the pull request again!

**Comment by nikhilmenghani** [comment]
@Namikazetoto you have to submit your contribution details before you can request for elite build.

**Comment by Trinketsz** [comment]
Ok

**Comment by nikgapps** [comment]
We cannot merge the pull request due to following reasons

- elite/10/PrivateGappsElitRMX1911.config is not a valid path, make sure your elite config is in elite/<android_version>/<elite_folder_name>

Kindly make the changes and send the pull request again!

**Comment by nikgapps** [comment]
Closing as no action was performed in last 24 hours

**Pull request closed without merging**
